coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%

comment:
  layout: "condensed_header, diff, flags, components"

component_management:
  individual_components:
    - component_id: api-calculator # this is an identifier that should not be changed
      name: calculator-test # this is a display name, and can be changed freely
      paths:
        - api/calculator/
    - component_id: api-smiles # this is an identifier that should not be changed
      name: smiles-test # this is a display name, and can be changed freely
      paths:
        - api/smiles/
